import random

RUTA_CABECERA = "cabecera.html"
RUTA_FOOTER = "footer.html"
IMG_ALT_ABSOLUTO = "img/missing.png"
IMG_ALT_RELATIVO = "../img/missing.png"


def arraglarImportsEnLinea(linea):
    linea = linea.replace("src=\"css", "src=\"../css").replace("src=\"js", "src=\"../js").replace("src=\"img",
                                                                                                  "src=\"../img")
    if "href=\"http" in linea:
        return linea
    linea = linea.replace("href=\"", "href=\"../")
    return linea


def htmlACadena(ruta):
    cadena = ""
    with open(ruta, 'r') as archivo:
        for linea in archivo:
            cadena = cadena + linea
    return cadena


def htmlACadenaConImportsArreglados(ruta):
    cadena = ""
    with open(ruta, 'r') as archivo:
        for linea in archivo:
            linea = arraglarImportsEnLinea(linea)
            cadena = cadena + linea
    return cadena


def crearElementoGridHTMLDeProducto(producto):
    return ("<div class=\"row row_item\">\n"
            + "<div class=\"col-sm-4\">\n"
            + "<figure>\n"
            + "<a href=\"" + producto.enlaceHTMLRelativo + "\">\n"
            + "<img class=\"img-fluid lazy\" src=\"" + producto.enlaceIMGAbsoluto + "\" data-src=\"" + producto.enlaceIMGAbsoluto + "\" onerror=\"this.onerror=null; this.src=\'"+ IMG_ALT_ABSOLUTO +"\'\" alt=\"\">\n"
            + "</a>\n"
            + "</figure>\n"
            + "</div>\n"
            + "<div class=\"col-sm-8\">\n"
            + "<a href=\"" + producto.enlaceHTMLRelativo + "\">\n"
            + "<h3>" + producto.titulo + "</h3>\n"
            + "</a>\n"
            + "<p>" + producto.descripcionCorta + "</p>\n"
            + "<div class=\"price_box\">\n"
            + "<span class=\"new_price\">" + producto.precio + "</span>\n"
            + "</div>\n"
            + "<ul>\n"
            + "<li><a href=\"#0\" class=\"btn_1\">Agregar al carrito</a></li>\n"
            + "</ul>\n"
            + "</div>\n"
            + "</div>\n")


def crearElementoCarruselHTMLDeProducto(producto):
    return (
            "<div class=\"item\">\n"
            + "<div class=\"grid_item\">\n"
            + "<figure>\n"
            + "<a href=\"" + producto.enlaceHTMLRelativo + "\">\n"
            + "<img class=\"owl-lazy\" src=\"" + producto.enlaceIMGRelativo + "\" data-src=\"" + producto.enlaceIMGRelativo + "\"  onerror=\"this.onerror=null; this.src=\'"+ IMG_ALT_RELATIVO +"\'\" alt=\"\">\n"
            + "</a>\n"
            + "</figure>\n"
            + "<a href=\"" + producto.enlaceHTMLRelativo + "\">\n"
            + "<h3>" + producto.titulo + "</h3>\n"
            + "</a>\n"
            + "<div class=\"price_box\">\n"
            + "<span class=\"new_price\">" + producto.precio + "</span>\n"
            + "</div>\n"
            + "<ul>\n"
            + "<li><a href=\"#0\" class=\"tooltip-1\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Add to cart\"><i class=\"ti-shopping-cart\"></i><span>Agregar al carrito</span></a></li>\n"
            + "</ul>\n"
            + "</div>\n"
            + "</div>\n")


def crearHojaHTMLDeProducto(producto, listaDeProductosEnCarrusel):
    cabecera = htmlACadenaConImportsArreglados(RUTA_CABECERA).encode('latin1')
    footer = htmlACadenaConImportsArreglados(RUTA_FOOTER).encode('latin1')
    html = (""
            + "<main>\n"
            + "<div class=\"container margin_30\">\n"
            + "<div class=\"row\">\n"
            + "<div class=\"col-lg-6 magnific-gallery\">\n"
            + "<p>\n"
            + "<a href=\"" + producto.enlaceIMGRelativo + "\" title=\"" + producto.titulo + "\" data-effect=\"mfp-zoom-in\"><img src=\"" + producto.enlaceIMGRelativo + "\" "
            + " onerror=\"this.onerror=null; this.src=\'"+ IMG_ALT_RELATIVO +"\'\" alt=\"\" class=\"img-fluid\"></a>\n"
            + "</p>\n"
            + "</div>\n"
            + "<div class=\"col-lg-6\" id=\"sidebar_fixed\">\n"
            + "<div class=\"breadcrumbs\">\n"
            + "<ul>\n"
            + "<li><a href=\"#\">Inicio</a></li>\n"
            + "<li><a href=\"#\">Español</a></li>\n"
            + "<li>" + producto.titulo + "</li>\n"
            + "</ul>\n"
            + "</div>\n"
            + "<!-- /page_header -->\n"
            + "<div class=\"prod_info\">\n"
            + "<h1>" + producto.titulo + "</h1>\n"
            + "<p><small>ISBN: " + producto.isbn + "</small><br/>" + producto.descripcion + "</p>\n"
            + "<div class=\"prod_options\">\n"
            + "<div class=\"row\">\n"
            + "<label class=\"col-xl-5 col-lg-5  col-md-6 col-6\"><strong>Cantidad</strong></label>\n"
            + "<div class=\"col-xl-4 col-lg-5 col-md-6 col-6\">\n"
            + "<div class=\"numbers-row\">\n"
            + "<input type=\"text\" value=\"1\" id=\"quantity_1\" class=\"qty2\" name=\"quantity_1\">\n"
            + "</div>\n"
            + "</div>\n"
            + "</div>\n"
            + "</div>\n"
            + "<div class=\"row\">\n"
            + "<div class=\"col-lg-5 col-md-6\">\n"
            + "<div class=\"price_main\"><span class=\"new_price\">" + producto.precio + "</span></div>\n"
            + "</div>\n"
            + "<div class=\"col-lg-4 col-md-6\">\n"
            + "<div class=\"btn_add_to_cart\"><a href=\"#0\" class=\"btn_1\">Agregar al carrito</a></div>\n"
            + "</div>\n"
            + "</div>\n"
            + "</div>\n"
            + "<!-- /prod_info -->\n"
            + "</div>\n"
            + "</div>\n"
            + "<!-- /row -->\n"
            + "</div>\n"
            + "<!-- /container -->\n"
            + "\n"
            + "<div class=\"tabs_product\">\n"
            + "<div class=\"container\">\n"
            + "<ul class=\"nav nav-tabs\" role=\"tablist\">\n"
            + "<li class=\"nav-item\">\n"
            + "<a id=\"tab-A\" href=\"#pane-A\" class=\"nav-link active\" data-toggle=\"tab\" role=\"tab\">Descripción</a>\n"
            + "</li>\n"
            + "</ul>\n"
            + "</div>\n"
            + "</div>\n"
            + "<!-- /tabs_product -->\n"
            + "<div class=\"tab_content_wrapper\">\n"
            + "<div class=\"container\">\n"
            + "<div class=\"tab-content\" role=\"tablist\">\n"
            + "<div id=\"pane-A\" class=\"card tab-pane fade show active\" role=\"tabpanel\" aria-labelledby=\"tab-A\">\n"
            + "<div class=\"card-header\" role=\"tab\" id=\"heading-A\">\n"
            + "<h5 class=\"mb-0\">\n"
            + "<a class=\"collapsed\" data-toggle=\"collapse\" href=\"#collapse-A\" aria-expanded=\"false\" aria-controls=\"collapse-A\">\n"
            + "Descripción\n"
            + "</a>\n"
            + "</h5>\n"
            + "</div>\n"
            + "<div id=\"collapse-A\" class=\"collapse\" role=\"tabpanel\" aria-labelledby=\"heading-A\">\n"
            + "<div class=\"card-body\">\n"
            + "<div class=\"row\">\n"
            + "<div class=\"col-md-6\">\n"
            + "<h3>Detalles</h3>\n"
            + "<p>" + producto.descripcion + "</p>\n"
            + "</div>\n"
            + "<div class=\"col-md-6\">\n"
            + "<h3>Especificaciones</h3>\n"
            + "<div class=\"table-responsive\">\n"
            + "<table class=\"table table-sm table-striped\">\n"
            + "<tbody>\n"
            + "<tr>\n"
            + "<td><strong>Marca</strong></td>\n"
            + "<td>" + producto.marca + "</td>\n"
            + "</tr>\n"
            + "<tr>\n"
            + "<td><strong>Área</strong></td>\n"
            + "<td>" + producto.area + "</td>\n"
            + "</tr>\n"
            + "<tr>\n"
            + "<td><strong>Sector</strong></td>\n"
            + "<td>" + producto.sector + "</td>\n"
            + "</tr>\n"
            + "<tr>\n"
            + "<td><strong>ISBN</strong></td>\n"
            + "<td>" + producto.isbn + "</td>\n"
            + "</tr>\n"
            + "</tbody>\n"
            + "</table>\n"
            + "</div>\n"
            + "<!-- /table-responsive -->\n"
            + "</div>\n"
            + "</div>\n"
            + "</div>\n"
            + "</div>\n"
            + "</div>\n"
            + "</div>\n"
            + "<!-- /tab-content -->\n"
            + "</div>\n"
            + "</div>\n"
            + "\n"
            + "<div class=\"container margin_60_35\">\n"
            + "<div class=\"main_title\">\n"
            + "<h2>Relacionados</h2>\n"
            + "<span>Libros</span>\n"
            + "<p>Si te gustó puede que también te interese</p>\n"
            + "</div>\n"
            + "<div class=\"owl-carousel owl-theme products_carousel\">\n"
            + random.choice(listaDeProductosEnCarrusel).replace("href=\"productos/", "href=\"")
            + "<!-- /item -->\n"
            + random.choice(listaDeProductosEnCarrusel).replace("href=\"productos/", "href=\"")
            + "<!-- /item -->\n"
            + random.choice(listaDeProductosEnCarrusel).replace("href=\"productos/", "href=\"")
            + "<!-- /item -->\n"
            + random.choice(listaDeProductosEnCarrusel).replace("href=\"productos/", "href=\"")
            + "<!-- /item -->\n"
            + random.choice(listaDeProductosEnCarrusel).replace("href=\"productos/", "href=\"")
            + "<!-- /item -->\n"
            + random.choice(listaDeProductosEnCarrusel).replace("href=\"productos/", "href=\"")
            + "</div>\n"
            + "<!-- /products_carousel -->\n"
            + "</div>\n"
            + "<!-- /container -->\n"
            + "\n"
            + "<div class=\"feat\">\n"
            + "<div class=\"container\">\n"
            + "<ul>\n"
            + "<li>\n"
            + "<div class=\"box\">\n"
            + "<i class=\"ti-gift\"></i>\n"
            + "<div class=\"justify-content-center\">\n"
            + "<h3>Envíos Internacionales</h3>\n"
            + "<p>Recibe tu libro en cualquier parte del mundo</p>\n"
            + "</div>\n"
            + "</div>\n"
            + "</li>\n"
            + "<li>\n"
            + "<div class=\"box\">\n"
            + "<i class=\"ti-wallet\"></i>\n"
            + "<div class=\"justify-content-center\">\n"
            + "<h3>Pagos Seguros</h3>\n"
            + "<p>Pagos 100% seguros</p>\n"
            + "</div>\n"
            + "</div>\n"
            + "</li>\n"
            + "<li>\n"
            + "<div class=\"box\">\n"
            + "<i class=\"ti-headphone-alt\"></i>\n"
            + "<div class=\"justify-content-center\">\n"
            + "<h3>Soporte 24/7 </h3>\n"
            + "<p>Soporte en línea siempre disponible</p>\n"
            + "</div>\n"
            + "</div>\n"
            + "</li>\n"
            + "</ul>\n"
            + "</div>\n"
            + "</div>\n"
            + "<!--/feat-->\n"
            + "</main>\n").encode('utf8')
    return cabecera + html + footer


def regresarElementoGridInvisible(elementoGrid):
    return elementoGrid.replace("display: block", "display: none")


def crearCatalogoHTML(listaDeProductosEnGrid):
    cabecera = htmlACadena(RUTA_CABECERA).encode('latin1')
    footer = htmlACadena(RUTA_FOOTER).encode('latin1')
    gridProductos = ""
    for index, producto in enumerate(listaDeProductosEnGrid):
        gridProductos = gridProductos + \
                        producto if index < 20 else regresarElementoGridInvisible(producto)
    html = ("<main>\n"
            + "            <div class=\"top_banner\">\n"
            + "    <div class=\"opacity-mask d-flex align-items-center\" data-opacity-mask=\"rgba(0, 0, 0, 0.3)\">\n"
            + "    <div class=\"container\">\n"
            + "    <h1>Catálogo</h1>\n"
            + "</div>\n"
            + "</div>\n"
            + "<img src=\"img/bannerCatalogo.jpg\" class=\"img-fluid\" alt=\"\">\n"
            + "</div>\n"
            + "<!-- /top_banner -->\n"
            + "<div class=\"container margin_30\">\n"
            + "<div class=\"row\">\n"
            + "<aside class=\"col-lg-3\" id=\"sidebar_fixed\">\n"
            + "<div class=\"filter_col\">\n"
            + "<div class=\"inner_bt\"><a href=\"#\" class=\"open_filters\"><i class=\"ti-close\"></i></a></div>\n"
            + "<div class=\"filter_type version_2\">\n"
            + "<h4><a href=\"#filter_1\" data-toggle=\"collapse\" class=\"opened\">Categorías</a></h4>\n"
            + "<div class=\"collapse show\" id=\"filter_1\">\n"
            + "<ul>\n"
            + "<li>\n"
            + "<label class=\"container_check\">Español <small>12</small>\n"
            + "<input type=\"checkbox\">\n"
            + "<span class=\"checkmark\"></span>\n"
            + "</label>\n"
            + "</li>\n"
            + "<li>\n"
            + "<label class=\"container_check\">ELT <small>24</small>\n"
            + "<input type=\"checkbox\">\n"
            + "<span class=\"checkmark\"></span>\n"
            + "</label>\n"
            + "</li>\n"
            + "<li>\n"
            + "<label class=\"container_check\">Readers <small>23</small>\n"
            + "<input type=\"checkbox\">\n"
            + "<span class=\"checkmark\"></span>\n"
            + "</label>\n"
            + "</li>\n"
            + "<li>\n"
            + "<label class=\"container_check\">Literatura <small>11</small>\n"
            + "<input type=\"checkbox\">\n"
            + "<span class=\"checkmark\"></span>\n"
            + "</label>\n"
            + "</li>\n"
            + "</ul>\n"
            + "</div>\n"
            + "<!-- /filter_type -->\n"
            + "</div>\n"
            + "<!-- /filter_type -->\n"
            + "<div class=\"filter_type version_2\">\n"
            + "<h4><a href=\"#filter_2\" data-toggle=\"collapse\" class=\"opened\">Sector</a></h4>\n"
            + "<div class=\"collapse show\" id=\"filter_2\">\n"
            + "<ul>\n"
            + "<li>\n"
            + "<label class=\"container_check\">Preescolar <small>06</small>\n"
            + "<input type=\"checkbox\">\n"
            + "<span class=\"checkmark\"></span>\n"
            + "</label>\n"
            + "</li>\n"
            + "<li>\n"
            + "<label class=\"container_check\">Primaria <small>12</small>\n"
            + "<input type=\"checkbox\">\n"
            + "<span class=\"checkmark\"></span>\n"
            + "</label>\n"
            + "</li>\n"
            + "<li>\n"
            + "<label class=\"container_check\">Secundaria <small>17</small>\n"
            + "<input type=\"checkbox\">\n"
            + "<span class=\"checkmark\"></span>\n"
            + "</label>\n"
            + "</li>\n"
            + "</ul>\n"
            + "</div>\n"
            + "</div>\n"
            + "<!-- /filter_type -->\n"
            + "<div class=\"filter_type version_2\">\n"
            + "<h4><a href=\"#filter_3\" data-toggle=\"collapse\" class=\"closed\">Marca</a></h4>\n"
            + "<div class=\"collapse\" id=\"filter_3\">\n"
            + "<ul>\n"
            + "<li>\n"
            + "<label class=\"container_check\">Eduvisión <small>11</small>\n"
            + "<input type=\"checkbox\">\n"
            + "<span class=\"checkmark\"></span>\n"
            + "</label>\n"
            + "</li>\n"
            + "<li>\n"
            + "<label class=\"container_check\">Edinun <small>08</small>\n"
            + "<input type=\"checkbox\">\n"
            + "<span class=\"checkmark\"></span>\n"
            + "</label>\n"
            + "</li>\n"
            + "<li>\n"
            + "<label class=\"container_check\">Eureka <small>05</small>\n"
            + "<input type=\"checkbox\">\n"
            + "<span class=\"checkmark\"></span>\n"
            + "</label>\n"
            + "</li>\n"
            + "<li>\n"
            + "<label class=\"container_check\">Latibooks <small>18</small>\n"
            + "<input type=\"checkbox\">\n"
            + "<span class=\"checkmark\"></span>\n"
            + "</label>\n"
            + "</li>\n"
            + "</ul>\n"
            + "</div>\n"
            + "</div>\n"
            + "<!-- /filter_type -->\n"
            + "<div class=\"filter_type version_2\">\n"
            + "<h4><a href=\"#filter_4\" data-toggle=\"collapse\" class=\"closed\">Precio</a></h4>\n"
            + "<div class=\"collapse\" id=\"filter_4\">\n"
            + "<ul>\n"
            + "<li>\n"
            + "<label class=\"container_check\">$0 — $50<small>11</small>\n"
            + "<input type=\"checkbox\">\n"
            + "<span class=\"checkmark\"></span>\n"
            + "</label>\n"
            + "</li>\n"
            + "<li>\n"
            + "<label class=\"container_check\">$50 — $100<small>08</small>\n"
            + "<input type=\"checkbox\">\n"
            + "<span class=\"checkmark\"></span>\n"
            + "</label>\n"
            + "</li>\n"
            + "<li>\n"
            + "<label class=\"container_check\">$100 — $150<small>05</small>\n"
            + "<input type=\"checkbox\">\n"
            + "<span class=\"checkmark\"></span>\n"
            + "</label>\n"
            + "</li>\n"
            + "<li>\n"
            + "<label class=\"container_check\">$150 — $200<small>18</small>\n"
            + "<input type=\"checkbox\">\n"
            + "<span class=\"checkmark\"></span>\n"
            + "</label>\n"
            + "</li>\n"
            + "</ul>\n"
            + "</div>\n"
            + "</div>\n"
            + "<!-- /filter_type -->\n"
            + "<div class=\"buttons\">\n"
            + "<a href=\"#0\" class=\"btn_1\">Filtrar</a> <a href=\"#0\" class=\"btn_1 gray\">Despejar</a>\n"
            + "</div>\n"
            + "</div>\n"
            + "</aside>\n"
            + "<!-- /col -->\n"
            + "<div class=\"col-lg-9\">"
            + gridProductos
            + "</div>\n"
            + "<!-- /col -->\n"
            + "</div>\n"
            + "<!-- /row -->\n"
            + "</div>\n"
            + "<!-- /container -->\n"
            + "</main>\n").encode('utf8')
    return cabecera + html + footer
